### ISSUE TITLE
Using Docker Bridge mode instead of Docker Host mode

### ISSUE THREAD

**Issue by AlexCxx** [nsudhanva/https-caddy-tailscale#2]
Hi,

Thanks for sharing this ! It's really helpful.

Do you think it's doable to adapt this sample to use Docker Bridge network mode instead of Docker Host network mode?
I tried to do it, without success.. (not really familiar with docker)

I saw that some people managed to do it on Nextcloud AIO GitHub: https://github.com/nextcloud/all-in-one/discussions/5439

Any thoughts?

Thanks!
Alex

**Comment by sen1ory** [comment]
hi,
if you wanna avoid exposing host network to tailscale, you can do something like:
```yml
version: "3.7"

# comment out, not needed, as network_mode: service:tailscale is used instead, now they're like on the same host
# NOTE: as now web1, web2, web3 are on the same network, their ports may collide, also, if web1 had port 8081, web2 8082, web3 8083, you could reach each of them from any container in the same network_mode by http://localhost:8081 or http://127.0.0.1:8082
# networks:
#  proxy-network:
#    name: proxy-network

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    hostname: caddy
    # put in the same network with tailscale without any bridges, as if they're on the same host
    network_mode: service:tailscale
#     networks:
#       - proxy-network
    depends_on:
      - tailscale 
      - web1
      - web2
      - web3
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./tailscale/tmp/tailscaled.sock:/var/run/tailscale/tailscaled.sock

  tailscale:
    env_file: .env
    container_name: tailscaled
    image: tailscale/tailscale
    # remove host exposure
#     network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale/varlib:/var/lib
      - ./tailscale/tmp:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale

  web1:
    image: httpd:latest
    container_name: web1
    # put in the same network with tailscale without any bridges, as if they're on the same host
    network_mode: service:tailscale
#     networks:
#       - proxy-network

  web2:
    image: httpd:latest
    container_name: web2
    # put in the same network with tailscale without any bridges, as if they're on the same host
    network_mode: service:tailscale
#     networks:
#       - proxy-network

  web3:
    image: httpd:latest
    container_name: web3
    # put in the same network with tailscale without any bridges, as if they're on the same host
    network_mode: service:tailscale
#     networks:
#       - proxy-network
```
